// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pharmacyPOS.API.Models;

#nullable disable

namespace pharmacyPOS.API.Migrations
{
    [DbContext(typeof(SethuwaPharmacyDbContext))]
    [Migration("20251215135349_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockMovement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantityChanged")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("SalesId")
                        .HasColumnType("bigint");

                    b.Property<long>("Stock_Id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("StockMovements");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Customer", b =>
                {
                    b.Property<string>("CustomerId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Customer_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Contact_Number");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Customer_Name");

                    b.Property<string>("CustomerStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Customer_Status");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email_Address");

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__8CB286B9E2DDE106");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.CustomerRecurrentItem", b =>
                {
                    b.Property<long>("RecurrentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Recurrent_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RecurrentId"));

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Customer_ID");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product_SKU");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("RecurrentId")
                        .HasName("PK__Customer__B535C77670592A73");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductSku");

                    b.ToTable("Customer_Recurrent_Items", (string)null);
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Employee_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Contact_Number");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email_Address");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Employee_Name");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Employee_Status");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password_Hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7811348181A106AF");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Glossary", b =>
                {
                    b.Property<string>("GlossaryId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Glossary_ID");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Brand_Name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("Low_Stock_Threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("GlossaryId")
                        .HasName("PK__Glossari__D5F2E44475609879");

                    b.HasIndex(new[] { "Name" }, "UQ__Glossari__737584F61C326F38")
                        .IsUnique();

                    b.ToTable("Glossaries");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Medicine", b =>
                {
                    b.Property<string>("MedicineId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Medicine_ID");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Brand_Name");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("GenericName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Generic_Name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LowStockThreshold")
                        .HasColumnType("int")
                        .HasColumnName("Low_Stock_Threshold");

                    b.Property<string>("Manufacture")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("RequiredPrescription")
                        .HasColumnType("bit")
                        .HasColumnName("Required_Prescription");

                    b.Property<string>("Strength")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MedicineId")
                        .HasName("PK__Medicine__5F0102352C5A171D");

                    b.HasIndex(new[] { "Name" }, "UQ__Medicine__737584F611D8362D")
                        .IsUnique();

                    b.ToTable("Medicines");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Product", b =>
                {
                    b.Property<string>("ProductSku")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product_SKU");

                    b.Property<string>("GlossaryId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Glossary_ID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicineId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Medicine_ID");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Product_Type");

                    b.HasKey("ProductSku")
                        .HasName("PK__Products__5C44DD333C7A5A01");

                    b.HasIndex("GlossaryId");

                    b.HasIndex("MedicineId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Purchase", b =>
                {
                    b.Property<string>("PurchaseId")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Purchase_ID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("Created_At")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("InvoiceDate")
                        .HasColumnType("date")
                        .HasColumnName("Invoice_Date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Invoice_Number");

                    b.Property<DateTime?>("PaymentCompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Payment_Completed_At");

                    b.Property<DateTime?>("PaymentCompletedAt1")
                        .HasColumnType("datetime")
                        .HasColumnName("PaymentCompletedAt");

                    b.Property<DateOnly?>("PaymentDueDate")
                        .HasColumnType("date")
                        .HasColumnName("Payment_Due_Date");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Payment_Method");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Payment_Status");

                    b.Property<string>("SupplierId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Supplier_ID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Total_Amount");

                    b.HasKey("PurchaseId")
                        .HasName("PK__Purchase__543E6DA34F2568D7");

                    b.HasIndex("SupplierId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.PurchaseItem", b =>
                {
                    b.Property<long>("PurchaseItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Purchase_Item_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("PurchaseItemId"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Cost_Price");

                    b.Property<DateOnly>("ExpireDate")
                        .HasColumnType("date")
                        .HasColumnName("Expire_Date");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product_SKU");

                    b.Property<string>("PurchaseId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Purchase_ID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Selling_Price");

                    b.HasKey("PurchaseItemId")
                        .HasName("PK__Purchase__4CEA41E2080BD38C");

                    b.HasIndex("ProductSku");

                    b.HasIndex("PurchaseId");

                    b.ToTable("Purchase_Items", (string)null);
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Sale", b =>
                {
                    b.Property<long>("SalesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Sales_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SalesId"));

                    b.Property<string>("BilledById")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Billed_By_ID");

                    b.Property<decimal?>("CustomerDiscountPercent")
                        .HasColumnType("decimal(5, 2)")
                        .HasColumnName("Customer_Discount_Percent");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Customer_ID");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("FinalAmountDue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Final_Amount_Due");

                    b.Property<string>("IssuedById")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Issued_By_ID");

                    b.Property<DateTime?>("PaymentCompletedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Payment_Completed_At");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Payment_Method");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Receipt_Number");

                    b.Property<decimal?>("RoundingDiscount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Rounding_Discount");

                    b.Property<string>("SaleStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Sale_Status");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Total_Amount");

                    b.HasKey("SalesId")
                        .HasName("PK__Sales__32123EFAAD35C0BE");

                    b.HasIndex("BilledById");

                    b.HasIndex("CustomerId");

                    b.HasIndex("IssuedById");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.SalesItem", b =>
                {
                    b.Property<long>("SalesItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Sales_Item_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SalesItemId"));

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product_SKU");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<long>("SalesId")
                        .HasColumnType("bigint")
                        .HasColumnName("Sales_ID");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Selling_Price");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Sub_Total");

                    b.HasKey("SalesItemId")
                        .HasName("PK__Sales_It__320F1BA37575F4B8");

                    b.HasIndex("ProductSku");

                    b.HasIndex("SalesId");

                    b.ToTable("Sales_Items", (string)null);
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Stock", b =>
                {
                    b.Property<long>("StockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Stock_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("StockId"));

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Cost_Price");

                    b.Property<DateOnly>("ExpireDate")
                        .HasColumnType("date")
                        .HasColumnName("Expire_Date");

                    b.Property<string>("LotNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Lot_Number");

                    b.Property<string>("ProductSku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Product_SKU");

                    b.Property<int>("QuantityOnHand")
                        .HasColumnType("int")
                        .HasColumnName("Quantity_on_Hand");

                    b.Property<decimal>("SellingPrice")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("Selling_Price");

                    b.HasKey("StockId")
                        .HasName("PK__Stock__EFA64EB85A10A757");

                    b.HasIndex("ProductSku");

                    b.HasIndex(new[] { "LotNumber" }, "UQ__Stock__B2FED760F263F927")
                        .IsUnique()
                        .HasFilter("[Lot_Number] IS NOT NULL");

                    b.ToTable("Stock", (string)null);
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Supplier", b =>
                {
                    b.Property<string>("SupplierId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Supplier_ID");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("BankAccountName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Bank_Account_Name");

                    b.Property<string>("BankAccountNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Bank_Account_Number");

                    b.Property<string>("BankBranchName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Bank_Branch_Name");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Bank_Name");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Contact_Number");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Contact_Person");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Email_Address");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Supplier_Name");

                    b.HasKey("SupplierId")
                        .HasName("PK__Supplier__83918D98532D7B48");

                    b.HasIndex(new[] { "SupplierName" }, "UQ__Supplier__C919E828292C941E")
                        .IsUnique();

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.CustomerRecurrentItem", b =>
                {
                    b.HasOne("pharmacyPOS.API.Models.Customer", "Customer")
                        .WithMany("CustomerRecurrentItems")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Customer___Custo__4AB81AF0");

                    b.HasOne("pharmacyPOS.API.Models.Product", "ProductSkuNavigation")
                        .WithMany("CustomerRecurrentItems")
                        .HasForeignKey("ProductSku")
                        .IsRequired()
                        .HasConstraintName("FK__Customer___Produ__4BAC3F29");

                    b.Navigation("Customer");

                    b.Navigation("ProductSkuNavigation");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Product", b =>
                {
                    b.HasOne("pharmacyPOS.API.Models.Glossary", "Glossary")
                        .WithMany("Products")
                        .HasForeignKey("GlossaryId")
                        .HasConstraintName("FK__Products__Glossa__4316F928");

                    b.HasOne("pharmacyPOS.API.Models.Medicine", "Medicine")
                        .WithMany("Products")
                        .HasForeignKey("MedicineId")
                        .HasConstraintName("FK__Products__Medici__4222D4EF");

                    b.Navigation("Glossary");

                    b.Navigation("Medicine");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Purchase", b =>
                {
                    b.HasOne("pharmacyPOS.API.Models.Supplier", "Supplier")
                        .WithMany("Purchases")
                        .HasForeignKey("SupplierId")
                        .IsRequired()
                        .HasConstraintName("FK__Purchases__Suppl__4F7CD00D");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.PurchaseItem", b =>
                {
                    b.HasOne("pharmacyPOS.API.Models.Product", "ProductSkuNavigation")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("ProductSku")
                        .IsRequired()
                        .HasConstraintName("FK__Purchase___Produ__534D60F1");

                    b.HasOne("pharmacyPOS.API.Models.Purchase", "Purchase")
                        .WithMany("PurchaseItems")
                        .HasForeignKey("PurchaseId")
                        .IsRequired()
                        .HasConstraintName("FK__Purchase___Purch__52593CB8");

                    b.Navigation("ProductSkuNavigation");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Sale", b =>
                {
                    b.HasOne("pharmacyPOS.API.Models.Employee", "BilledBy")
                        .WithMany("SaleBilledBies")
                        .HasForeignKey("BilledById")
                        .HasConstraintName("FK__Sales__Billed_By__5AEE82B9");

                    b.HasOne("pharmacyPOS.API.Models.Customer", "Customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Sales__Customer___5BE2A6F2");

                    b.HasOne("pharmacyPOS.API.Models.Employee", "IssuedBy")
                        .WithMany("SaleIssuedBies")
                        .HasForeignKey("IssuedById")
                        .IsRequired()
                        .HasConstraintName("FK__Sales__Issued_By__59FA5E80");

                    b.Navigation("BilledBy");

                    b.Navigation("Customer");

                    b.Navigation("IssuedBy");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.SalesItem", b =>
                {
                    b.HasOne("pharmacyPOS.API.Models.Product", "ProductSkuNavigation")
                        .WithMany("SalesItems")
                        .HasForeignKey("ProductSku")
                        .IsRequired()
                        .HasConstraintName("FK__Sales_Ite__Produ__5FB337D6");

                    b.HasOne("pharmacyPOS.API.Models.Sale", "Sales")
                        .WithMany("SalesItems")
                        .HasForeignKey("SalesId")
                        .IsRequired()
                        .HasConstraintName("FK__Sales_Ite__Sales__5EBF139D");

                    b.Navigation("ProductSkuNavigation");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Stock", b =>
                {
                    b.HasOne("pharmacyPOS.API.Models.Product", "ProductSkuNavigation")
                        .WithMany("Stocks")
                        .HasForeignKey("ProductSku")
                        .IsRequired()
                        .HasConstraintName("FK__Stock__Product_S__571DF1D5");

                    b.Navigation("ProductSkuNavigation");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Customer", b =>
                {
                    b.Navigation("CustomerRecurrentItems");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Employee", b =>
                {
                    b.Navigation("SaleBilledBies");

                    b.Navigation("SaleIssuedBies");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Glossary", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Medicine", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Product", b =>
                {
                    b.Navigation("CustomerRecurrentItems");

                    b.Navigation("PurchaseItems");

                    b.Navigation("SalesItems");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Purchase", b =>
                {
                    b.Navigation("PurchaseItems");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Sale", b =>
                {
                    b.Navigation("SalesItems");
                });

            modelBuilder.Entity("pharmacyPOS.API.Models.Supplier", b =>
                {
                    b.Navigation("Purchases");
                });
#pragma warning restore 612, 618
        }
    }
}
